---
- name: install and run kibana
  hosts: master
  become: yes

  vars:
    elastic_servers: []

  tasks:
  - name: create server list
    set_fact:
      elastic_servers: "{{ elastic_servers + [ 'http://' + hostvars[item].internal_ip + ':9200' ] }}"
    loop: "{{ groups['master'] }}"
    delegate_to: localhost
  
  - name: kibana role
    include_role:
      name: kibana
    vars:
      kibana_directory: /opt/kibana
      kibana_elasticsearch_urls: "{{ elastic_servers }}"
      kibana_token: AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuX2dHU25Pb29CTlNTNjkyNExqM3N5OlNkNnlJdy1uVE1tVmpZcmxIeEtOTUE
...