---
- name: download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{docker_compose_os}}-{{docker_compose_arch}}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
...
