---
- name: install packages
  apt:
    name:
      - jq
      - zip
    state: present

- name: upload .zip-file
  unarchive:
    src: files/vault_1.10.3_linux_amd64.zip
    dest: /usr/local/bin

- name: create .service file for dev mode
  template:
    src: templates/vault.service.j2
    dest: /etc/systemd/system/vault.service
  notify: systemd reload

- name: force handler right now
  meta: flush_handlers
...